version: "3"
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    user: "0"
    volumes:
      - ../Data/grafana:/var/lib/grafana
    environment:
      - "FG_SERVER_ROOT_URL=CHANGEME.example.com"
    labels:
      # Traefik Labels
      - "traefik.enable=true"
      # HTTPS Labels
      - "traefik.http.routers.grafana.rule=Host(`localhost`)" # Domain Name
      - "traefik.http.routers.grafana.entrypoints=web-secure"
      - "traefik.http.routers.grafana.middlewares=default-headers@file"
      - "traefik.http.routers.grafana.service=grafana"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000" # Proxied Port
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    hostname: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - ../Data/influxdb:/var/lib/influxdb
      - ../Config/influxdb-scripts:/docker-entrypoint-initdb.d
    environment:
      - "INFLUXDB_ADMIN_USER=admin"
      - "INFLUXDB_ADMIN_PASSWORD=changeme"
