version: "3"
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    user: "0"
    volumes:
      - ../Data/grafana:/var/lib/grafana
    environment:
      - "FG_SERVER_ROOT_URL=CHANGEME.example.com"
    labels:
      # Traefik Labels
      - "traefik.enable=true"
      # HTTPS Labels
      - "traefik.http.routers.grafana.rule=Host(`localhost`)" # Domain Name
      - "traefik.http.routers.grafana.entrypoints=web-secure"
      - "traefik.http.routers.grafana.middlewares=default-headers@file"
      - "traefik.http.routers.grafana.service=grafana"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000" # Proxied Port
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    hostname: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - ../Data/influxdb:/var/lib/influxdb
      - ../Config/influxdb-scripts:/docker-entrypoint-initdb.d
    environment:
      - "INFLUXDB_ADMIN_USER=admin"
      - "INFLUXDB_ADMIN_PASSWORD=changeme"
  # Just for collecting sample metrics from this host
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    hostname: telegraf
    restart: unless-stopped
    ports:
      - "8888:8888"
    volumes:
      - "/:/hostfs:ro"
      - "/etc:/hostfs/etc:ro"
      - "/proc:/hostfs/proc:ro"
      - "/sys:/hostfs/sys:ro"
      - "/var:/hostfs/var:ro"
      - "/run:/hostfs/run:ro"
      - "../Config/telegraf.conf:/etc/telegraf/telegraf.conf"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      - "HOST_ETC=/hostfs/etc"
      - "HOST_PROC=/hostfs/proc"
      - "HOST_SYS=/hostfs/sys"
      - "HOST_VAR=/hostfs/var"
      - "HOST_RUN=/hostfs/run"
      - "HOST_MOUNT_PREFIX=/hostfs"
