version: "3"
services:
  # Just for collecting sample metrics from this host
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    hostname: telegraf
    restart: unless-stopped
    ports:
      - "8888:8888"
    volumes:
      - "/:/hostfs:ro"
      - "/etc:/hostfs/etc:ro"
      - "/proc:/hostfs/proc:ro"
      - "/sys:/hostfs/sys:ro"
      - "/var:/hostfs/var:ro"
      - "/run:/hostfs/run:ro"
      - "../Config/telegraf.conf:/etc/telegraf/telegraf.conf"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      - "HOST_ETC=/hostfs/etc"
      - "HOST_PROC=/hostfs/proc"
      - "HOST_SYS=/hostfs/sys"
      - "HOST_VAR=/hostfs/var"
      - "HOST_RUN=/hostfs/run"
      - "HOST_MOUNT_PREFIX=/hostfs"
